### ISSUE TITLE
wonder how to visualize the sensitive maps.

### ISSUE THREAD

**Issue by kkkcx** [shikiw/SI-Adv#1]
Thanks for your great work. 
I wonder how to visualize the sensitive maps as in your paper.
Thank you in advance!

**Comment by shikiw** [comment]
Thanks for your appreciation!
In fact, the sensitive scores can be obtained here:
https://github.com/shikiw/SI-Adv/blob/63f082dc8b844da96eca6643d9666f4c1b215e61/attacks.py#L524
then you can concatenate the point coordinates with these scores, i.e., (x, y, z, score), and apply this function: 
https://github.com/shikiw/SI-Adv/blob/63f082dc8b844da96eca6643d9666f4c1b215e61/main.py#L75-L86
to save the concatenated result into .txt format (other point cloud formats are also fine).
Each line of the .txt file corresponds to the (x, y, z, score) of each point. 
With this file, the sensitive map can be visualized by MeshLab or blensor as you like :)

**Comment by kkkcx** [comment]
Thank you for your detailed reply!

**Comment by ashwin-phadke** [comment]
Hello,

pretty much a noob here and I am still wondering how to render. I am unable to completely understand how to 

> then you can concatenate the point coordinates with these scores, i.e., (x, y, z, score), and apply this function:

do this part here, I am assuming that the part you mentioned is already available at the line number 524 as:
`sorted_point_list = sorted(point_list, key=lambda c: c[2], reverse=True)`

I am using the following method to execute with the target method as ifgm_ours:
`python main.py --transfer_attack_method ifgm_ours 
` 
Could you guide me here? Appreciate your work and the help. Thanks.

**Comment by shikiw** [comment]
> Hello,
> 
> pretty much a noob here and I am still wondering how to render. I am unable to completely understand how to
> 
> > then you can concatenate the point coordinates with these scores, i.e., (x, y, z, score), and apply this function:
> 
> do this part here, I am assuming that the part you mentioned is already available at the line number 524 as: `sorted_point_list = sorted(point_list, key=lambda c: c[2], reverse=True)`
> 
> I am using the following method to execute with the target method as ifgm_ours: `python main.py --transfer_attack_method ifgm_ours ` Could you guide me here? Appreciate your work and the help. Thanks.

Thanks for your appreciation!

The part at Line 524 is used for ranking the point in a descending order according to their sensitive scores, which is not necessary for visualization since visualizing a point cloud is usually independent of the point order in the point cloud data. 
Therefore, to realize this part: 
> then you can concatenate the point coordinates with these scores, i.e., (x, y, z, score), and apply this function:

First, we have the benign point cloud (x, y, z) with the shape as ![](http://latex.codecogs.com/gif.latex?N\times3) and the sensitive scores corresponding to these ![](http://latex.codecogs.com/gif.latex?N) points with the shape as ![](http://latex.codecogs.com/gif.latex?N\times1). 
Then, we can concatenate them and acquire the tensor (x, y, z, score) with the shape as ![](http://latex.codecogs.com/gif.latex?N\times4). 
Finally, we can apply this function:
https://github.com/shikiw/SI-Adv/blob/63f082dc8b844da96eca6643d9666f4c1b215e61/main.py#L75-L86
to save the tensor (x, y, z, score) into the .txt format, where each line means (x, y, z, R, G, B). Different RGB colors indicate different sensitive scores (Also, you can change to use other color styles). 
We can import the .txt file in MeshLab and the point cloud sensitivity map will be visualized :)

**Comment by ashwin-phadke** [comment]
Great, thanks for sharing and I'll work on that. However, I had one other question unrelated to this topic, is there any way I can speed up the dataset loading process, it looks like as of now it takes upwards of 15 mins to load the entire dataset. Let me know if I am missing something or if anything can be done about it.

Thanks.

Edit: The way I am loading dataset is mounting the code directory that has the dataset with type bind to a docker container.

**Comment by shikiw** [comment]
> Great, thanks for sharing and I'll work on that. However, I had one other question unrelated to this topic, is there any way I can speed up the dataset loading process, it looks like as of now it takes upwards of 15 mins to load the entire dataset. Let me know if I am missing something or if anything can be done about it.
> 
> Thanks.
> 
> Edit: The way I am loading dataset is mounting the code directory that has the dataset with type bind to a docker container.

When running the code for the first time, it will take a few mins to automatically compile the cuda extension for CurveNet. So I guess the mentioned 15 mins are taken for compiling this cuda extension rather than loading the dataset. Will it be quite faster when you run the code for the second time? If not, I guess I also have no idea about how to deal with it.
