### ISSUE TITLE
How to implement defense

### ISSUE THREAD

**Issue by Daniel-xsy** [shikiw/SI-Adv#4]
Thanks for your great work! I'm a little bit confused about the attack pipeline.

I notice that you put the `defense_head`(e.g., `sor`) inside the attack iterations by:
```python
if not self.defense_method is None:
    logits = self.classifier(self.pre_head(inputs.detach()))
else:
    logits = self.classifier(inputs.detach()) # [1, num_class]
```
However, in the implementation of `IF-Defense`, they do not put the `sor` in the attack iterations to generate adversarial points. I think your setting simulates where the attacker gets full information of the model **AND** the defense methods while the `IF-Defense` assume the attack only knows the model but does not know the defense methods.

I also tried the 2nd setting (e.g., do not use `defense_head` in the attack iterations) and found the ASR of `SI-Adv` largely decreased. I'm wondering which setting is more valid.

Just as the author of `IF-Defense` mentioned in https://github.com/Wuziyi616/IF-Defense/issues/12, I think the `sor` defense is also non-differentiable, so can we plug it into the attack iterations?

**Comment by shikiw** [comment]
Hi, 

Thanks for your interest! In fact, I was also confused about this issue before and asked the author of [SOR&DUP-Net](https://github.com/RyanHangZhou/tensorflow-DUP-Net) about the defense setting. The original SOR implementation is non-differentiable, so that its robustness evaluation against "white-box" attacks (e.g., PGD) is under the "gray-box" setting. Therefore, it is hard to compare it with some defenses like adversarial training. 

As I understand it, the 1st setting (white-box setting) means that the attacker can access to full information including the defense methods. So I rewrote the SOR code into a differentiable version [here](https://github.com/shikiw/SI-Adv/blob/main/baselines/defense/drop_points/SOR.py) to implement the white-box evaluation. 

Overall, both settings are okay for attack evaluation (i.e., white-box for the 1st setting and gray-box for the 2nd setting), while the 1st setting is more common and easy for attackers. But if we need to evaluate a newly proposed defense method, the 1st setting is not optional but necessary I think. 

I hope this will be helpful for you!

**Comment by Daniel-xsy** [comment]
I think I'm more clear about this now, thanks for your kind and detailed reply!
